#!/usr/bin/env bash

# Ask for the administrator password upfront
sudo -v

# ==============================================================================
# Ruby gems
# ==============================================================================

sudo gem install sass
# If sass watcher warns about rb-fsevent:
# sudo gem install --version '~> 0.9' rb-fsevent

# ==============================================================================
# Node packages
# ==============================================================================

npm install -g grunt-cli
npm install -g bower
npm install -g jshint
npm install -g eslint
npm install -g weinre
npm install -g uglify-js
npm install -g iectrl
